# Generated by Django 5.0.4 on 2024-06-05 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='initiator', to=settings.AUTH_USER_MODEL)),
                ('last_unread_message_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(max_length=333)),
                ('message_date_time', models.DateTimeField(auto_now_add=True)),
                ('message_unread', models.BooleanField(default=True)),
                ('message_author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('message_to_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_messages.conversations')),
            ],
        ),
    ]
