# Generated by Django 5.0.4 on 2024-07-14 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryuser',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
