# Generated by Django 5.0.4 on 2024-05-15 19:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=234)),
                ('description', models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Fantasy', 'Fantasy'), ('Novel', 'Novel'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Crime', 'Crime'), ('Horror', 'Horror'), ('Memoir', 'Memoir'), ('Biography', 'Biography'), ('Poetry', 'Poetry'), ('History', 'History'), ('Other', 'Other')], max_length=30)),
                ('year_of_publication', models.PositiveIntegerField()),
                ('borrower', models.CharField(max_length=50, null=True)),
                ('borrow_counter', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('return_date', models.DateField(default=None, null=True)),
                ('is_borrow', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.authors')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.publishers')),
            ],
            options={
                'ordering': ('-book_id',),
            },
        ),
    ]
